"""add certificate path

Revision ID: a654ae0be342
Revises: c6caf70afc0f
Create Date: 2026-08-02 15:02:45.917673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a654ae0be342'
down_revision: Union[str, Sequence[str], None] = 'c6caf70afc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('certificate_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'certificate_path')
    # ### end Alembic commands ###
