"""add officer role

Revision ID: fe210ea4a3b7
Revises: 3e6a93e876d6
Create Date: 2026-08-03 20:53:38.215425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe210ea4a3b7'
down_revision: Union[str, Sequence[str], None] = '3e6a93e876d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'citizens',
        sa.Column(
            'is_officer',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )

    op.alter_column(
        'citizens',
        'is_officer',
        server_default=None,
    ) # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citizens', 'is_officer')
    # ### end Alembic commands ###
