import React, { useEffect, useState } from "react";
import api from "../api/axios";

export default function Phone() {
    const [otp, setOtp] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        let mounted = true;

        async function fetchOtp() {
            try {
                const res = await api.get("/otp/dev-latest");
                if (mounted) {
                    setOtp(res.data.otp);
                }
            } catch (e) {
                if (mounted) setOtp(null);
            } finally {
                if (mounted) setLoading(false);
            }
        }

        fetchOtp();
        const interval = setInterval(fetchOtp, 5000);
        return () => {
            mounted = false;
            clearInterval(interval);
        };
    }, []);

    return (
        <div style={{ textAlign: "center", marginTop: "4rem" }}>
            <h1>VaaniSeva</h1>
            <h2>Development OTP</h2>

            <div style={{ fontSize: "2rem", margin: "2rem" }}>
                {loading ? "Loading..." : otp ?? "No OTP generated by the system yet."}
            </div>

            <div>Latest OTP generated by the system.</div>
        </div>
    );
}
